# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FirebaseAuthSandbox' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FirebaseAuthSandbox
  pod 'FacebookLogin'
  pod 'FBSDKCoreKit', '4.38.1'
  pod 'FBSDKLoginKit', '4.38.1'

  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
end
